name = "Mogra"
license = "MIT"
licenselink = "https://github.com/meghprkh/mogra-hugo-theme/blob/master/LICENSE"
description = "Simple clean theme. Suitable for Math/Tech blogs."
homepage = "https://github.com/meghprkh/mogra-hugo-theme/"
tags = ["blog", "plain", "simple", "clean"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Megh Parikh"
  homepage = "https://github.com/meghprkh"

# If porting an existing theme
[original]
  name = "Vimux"
  homepage = "https://github.com/vimux/blank"
  repo = "https://github.com/vimux/blank"
